// <auto-generated />
using Assignment2EF.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment2EF.Migrations
{
    [DbContext(typeof(WA_Context))]
    [Migration("20221109032756_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assignment2EF.Models.Enrollement", b =>
                {
                    b.Property<int>("EnrollementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollementId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EnrollementId");

                    b.ToTable("Enrollements");
                });

            modelBuilder.Entity("Assignment2EF.Models.Workshop", b =>
                {
                    b.Property<int>("WorkshopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkshopId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Information")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkshopId");

                    b.ToTable("Workshops");
                });

            modelBuilder.Entity("EnrollementWorkshop", b =>
                {
                    b.Property<int>("EnrollementsEnrollementId")
                        .HasColumnType("int");

                    b.Property<int>("WorkshopsWorkshopId")
                        .HasColumnType("int");

                    b.HasKey("EnrollementsEnrollementId", "WorkshopsWorkshopId");

                    b.HasIndex("WorkshopsWorkshopId");

                    b.ToTable("EnrollementWorkshop");
                });

            modelBuilder.Entity("EnrollementWorkshop", b =>
                {
                    b.HasOne("Assignment2EF.Models.Enrollement", null)
                        .WithMany()
                        .HasForeignKey("EnrollementsEnrollementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment2EF.Models.Workshop", null)
                        .WithMany()
                        .HasForeignKey("WorkshopsWorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
